### ISSUE TITLE
Combination of fast_rnnt and fast_emit

### ISSUE THREAD

**Issue by Butterfly-c** [danpovey/fast_rnnt#12]
Is there any version that take advantage of fast_emit?

**Comment by pkufool** [comment]
Sorry for late reply, we have a discussion in k2 repository (https://github.com/k2-fsa/k2/issues/955) and we are doing experiments, finally we will add something to make symbols emit earier.

**Comment by pkufool** [comment]
@Butterfly-c  The delay_penalty in https://github.com/k2-fsa/k2/issues/955 has been merged, you can try it.  It behaves as good as fast_emit. If you really want the fast_emit, you can try https://github.com/k2-fsa/k2/pull/1069 (by installing k2 or modifying fast_rnnt according to this PR).

**Comment by Li-jianqun** [comment]
![image](https://user-images.githubusercontent.com/56469483/199216221-be70ed62-311f-4212-b5db-05db8ecfb122.png)

**Comment by Li-jianqun** [comment]
help help help

**Comment by csukuangfj** [comment]
Please post, all, all, of the logs. The screenshot contains little information and it is hard for us to figure out what bad things happened.

**Comment by Li-jianqun** [comment]
![image](https://user-images.githubusercontent.com/56469483/199218876-4238d3d8-97a9-474b-b69e-d0e5d701e99a.png)

**Comment by Li-jianqun** [comment]
![image](https://user-images.githubusercontent.com/56469483/199219105-3dcb2b8d-d443-4bfd-85d6-4c82e5842cbb.png)

**Comment by csukuangfj** [comment]
please first use
```bash
pip install cmake
```
and then re-try.

**Comment by Li-jianqun** [comment]
![image](https://user-images.githubusercontent.com/56469483/199387511-8e2833fe-9d31-40ea-b394-4267c7e0aca2.png)
Still no success after pip install cmake

**Comment by csukuangfj** [comment]
Please post, all, all, of the logs. The screenshot contains little information and it is hard for us to figure out what bad things happened.

**Comment by Li-jianqun** [comment]
Collecting fast_rnnt
  Using cached fast_rnnt-1.2.tar.gz (63 kB)
Requirement already satisfied: torch>=1.5 in /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages (from fast_rnnt) (1.8.0)
Requirement already satisfied: typing_extensions in /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages (from torch>=1.5->fast_rnnt) (3.10.0.2)
Requirement already satisfied: numpy in /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages (from torch>=1.5->fast_rnnt) (1.21.2)
Building wheels for collected packages: fast-rnnt
  Building wheel for fast-rnnt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/env/Miniconda/envs/antiFraud/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"'; __file__='"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/project/tmp/pip-wheel-gjqz9j4h
       cwd: /data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/
  Complete output (123 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/fast_rnnt
  copying fast_rnnt/python/fast_rnnt/__init__.py -> build/lib.linux-x86_64-3.8/fast_rnnt
  copying fast_rnnt/python/fast_rnnt/mutual_information.py -> build/lib.linux-x86_64-3.8/fast_rnnt
  copying fast_rnnt/python/fast_rnnt/rnnt_loss.py -> build/lib.linux-x86_64-3.8/fast_rnnt
  running build_ext
  Setting PYTHON_EXECUTABLE to /data/env/Miniconda/envs/antiFraud/bin/python
  build command is:
  
              cd build/temp.linux-x86_64-3.8
  
              cmake -DCMAKE_BUILD_TYPE=Release -DFT_BUILD_TESTS=OFF -DPYTHON_EXECUTABLE=/data/env/Miniconda/envs/antiFraud/bin/python /data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902
  
              make  -j  _fast_rnnt
  
  -- C++ Standard version: 14
  -- No NVCC detected. Disable CUDA support
  -- Enabled languages: CXX
  -- The CXX compiler identification is GNU 7.3.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading pybind11
  -- pybind11 is downloaded to /tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/_deps/pybind11-src
  -- pybind11 v2.6.0
  CMake Warning (dev) at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/cmake/data/share/cmake-3.24/Modules/CMakeDependentOption.cmake:89 (message):
    Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
    Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.
  Call Stack (most recent call first):
    build/temp.linux-x86_64-3.8/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PythonInterp: /data/env/Miniconda/envs/antiFraud/bin/python (found version "3.8.12")
  -- Found PythonLibs: /data/env/Miniconda/envs/antiFraud/lib/libpython3.8.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Python executable: /data/env/Miniconda/envs/antiFraud/bin/python
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found CUDA: /usr/local/cuda (found version "9.2")
  -- Caffe2: CUDA detected: 9.2
  -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
  -- Caffe2: CUDA toolkit directory: /usr/local/cuda
  -- Caffe2: Header version is: 9.2
  -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)
  CMake Warning at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
    Caffe2: Cannot find cuDNN library.  Turning the option off
  Call Stack (most recent call first):
    /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
    /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
    cmake/torch.cmake:11 (find_package)
    CMakeLists.txt:135 (include)
  
  
  -- /usr/local/cuda/lib64/libnvrtc.so shorthash is 3fc78a74
  -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0 7.0 7.0 7.0 7.0
  -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
  CMake Error at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
    Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
    libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
  Call Stack (most recent call first):
    /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
    cmake/torch.cmake:11 (find_package)
    CMakeLists.txt:135 (include)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
  make: *** 没有规则可制作目标“_fast_rnnt”。 停止。
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py", line 105, in <module>
      setuptools.setup(
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py", line 59, in build_extension
      raise Exception(
  Exception:
  Build fast_rnnt failed. Please check the error message.
  You can ask for help by creating an issue on GitHub.
  
  Click:
        https://github.com/danpovey/fast_rnnt/issues/new
  
  ----------------------------------------
  ERROR: Failed building wheel for fast-rnnt
  Running setup.py clean for fast-rnnt
Failed to build fast-rnnt
Installing collected packages: fast-rnnt
    Running setup.py install for fast-rnnt ... error
    ERROR: Command errored out with exit status 1:
     command: /data/env/Miniconda/envs/antiFraud/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"'; __file__='"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/project/tmp/pip-record-zzspeaaw/install-record.txt --single-version-externally-managed --compile --install-headers /data/env/Miniconda/envs/antiFraud/include/python3.8/fast-rnnt
         cwd: /data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/
    Complete output (125 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/fast_rnnt
    copying fast_rnnt/python/fast_rnnt/__init__.py -> build/lib.linux-x86_64-3.8/fast_rnnt
    copying fast_rnnt/python/fast_rnnt/mutual_information.py -> build/lib.linux-x86_64-3.8/fast_rnnt
    copying fast_rnnt/python/fast_rnnt/rnnt_loss.py -> build/lib.linux-x86_64-3.8/fast_rnnt
    running build_ext
    Setting PYTHON_EXECUTABLE to /data/env/Miniconda/envs/antiFraud/bin/python
    build command is:
    
                cd build/temp.linux-x86_64-3.8
    
                cmake -DCMAKE_BUILD_TYPE=Release -DFT_BUILD_TESTS=OFF -DPYTHON_EXECUTABLE=/data/env/Miniconda/envs/antiFraud/bin/python /data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902
    
                make  -j  _fast_rnnt
    
    -- C++ Standard version: 14
    -- No NVCC detected. Disable CUDA support
    -- Enabled languages: CXX
    -- The CXX compiler identification is GNU 7.3.1
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Downloading pybind11
    -- pybind11 is downloaded to /tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/_deps/pybind11-src
    -- pybind11 v2.6.0
    CMake Warning (dev) at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/cmake/data/share/cmake-3.24/Modules/CMakeDependentOption.cmake:89 (message):
      Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
      Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    Call Stack (most recent call first):
      build/temp.linux-x86_64-3.8/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found PythonInterp: /data/env/Miniconda/envs/antiFraud/bin/python (found version "3.8.12")
    -- Found PythonLibs: /data/env/Miniconda/envs/antiFraud/lib/libpython3.8.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Python executable: /data/env/Miniconda/envs/antiFraud/bin/python
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found CUDA: /usr/local/cuda (found version "9.2")
    -- Caffe2: CUDA detected: 9.2
    -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda
    -- Caffe2: Header version is: 9.2
    -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)
    CMake Warning at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
      Caffe2: Cannot find cuDNN library.  Turning the option off
    Call Stack (most recent call first):
      /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
      /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      cmake/torch.cmake:11 (find_package)
      CMakeLists.txt:135 (include)
    
    
    -- /usr/local/cuda/lib64/libnvrtc.so shorthash is 3fc78a74
    -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0 7.0 7.0 7.0 7.0
    -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
    CMake Error at /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
      Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
      libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
    Call Stack (most recent call first):
      /data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      cmake/torch.cmake:11 (find_package)
      CMakeLists.txt:135 (include)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    make: *** 没有规则可制作目标“_fast_rnnt”。 停止。
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py", line 105, in <module>
        setuptools.setup(
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/data/env/Miniconda/envs/antiFraud/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py", line 59, in build_extension
        raise Exception(
    Exception:
    Build fast_rnnt failed. Please check the error message.
    You can ask for help by creating an issue on GitHub.
    
    Click:
        https://github.com/danpovey/fast_rnnt/issues/new
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/env/Miniconda/envs/antiFraud/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"'; __file__='"'"'/data/project/tmp/pip-install-9iw1isrs/fast-rnnt_a4d5b095de2f4376aceff9c2b4450902/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/project/tmp/pip-record-zzspeaaw/install-record.txt --single-version-externally-managed --compile --install-headers /data/env/Miniconda/envs/antiFraud/include/python3.8/fast-rnnt Check the logs for full command output.

**Comment by Li-jianqun** [comment]
The above is all the error log

**Comment by csukuangfj** [comment]
> -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)

From the error log, you have not installed cuDNN yet.

Also, your installed CUDA is 9.2, which is quite old. I am not sure whether it works.
I suggest that you upgrade your CUDA and PyTorch.

**Comment by Li-jianqun** [comment]
running install
running bdist_egg
running egg_info
writing fast_rnnt.egg-info/PKG-INFO
writing dependency_links to fast_rnnt.egg-info/dependency_links.txt
writing requirements to fast_rnnt.egg-info/requires.txt
writing top-level names to fast_rnnt.egg-info/top_level.txt
reading manifest file 'fast_rnnt.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'fast_rnnt.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying fast_rnnt/python/fast_rnnt/__init__.py -> build/lib.linux-x86_64-3.8/fast_rnnt
running build_ext
Setting PYTHON_EXECUTABLE to /data/env/Miniconda/envs/antiFraud/bin/python
build command is:

            cd build/temp.linux-x86_64-3.8

            cmake -DCMAKE_BUILD_TYPE=Release -DFT_BUILD_TESTS=OFF -DPYTHON_EXECUTABLE=/data/env/Miniconda/envs/antiFraud/bin/python /data5/E2E_WENET/fast_rnnt

            make  -j  _fast_rnnt
        
-- C++ Standard version: 14
-- No NVCC detected. Disable CUDA support
-- Enabled languages: CXX
-- The CXX compiler identification is GNU 7.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading pybind11
[ 11%] Creating directories for 'pybind11-populate'
[ 22%] Performing download step (download, verify and extract) for 'pybind11-populate'
-- verifying file...
       file='/data5/E2E_WENET/fast_rnnt/build/temp.linux-x86_64-3.8/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.6.0.tar.gz'
-- SHA256 hash of
    /data5/E2E_WENET/fast_rnnt/build/temp.linux-x86_64-3.8/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.6.0.tar.gz
  does not match expected value
    expected: '90b705137b69ee3b5fc655eaca66d0dc9862ea1759226f7ccd3098425ae69571'
      actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/data5/E2E_WENET/fast_rnnt/build/temp.linux-x86_64-3.8/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.6.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
CMake Error at pybind11-subbuild/pybind11-populate-prefix/src/pybind11-populate-stamp/download-pybind11-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
          status_code: 56
          status_string: "Failure when receiving data from the peer"
          log:
          --- LOG BEGIN ---
            Trying 20.205.243.166:443...

  Connected to github.com (20.205.243.166) port 443 (#0)

  ALPN: offers h2

  ALPN: offers http/1.1

  TLSv1.0 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  TLSv1.2 (IN), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.3 (IN), TLS handshake, Server hello (2):

  [122 bytes data]

  TLSv1.2 (IN), TLS header, Finished (20):

  [5 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):

  [19 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Certificate (11):

  [2459 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, CERT verify (15):

  [79 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Finished (20):

  [36 bytes data]

  TLSv1.2 (OUT), TLS header, Finished (20):

  [5 bytes data]

  TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (OUT), TLS handshake, Finished (20):

  [36 bytes data]

  SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256

  ALPN: server accepted h2

  Server certificate:

   subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
   start date: Mar 15 00:00:00 2022 GMT
   expire date: Mar 15 23:59:59 2023 GMT
   subjectAltName: host "github.com" matched cert's "github.com"
   issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
   SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

  Using HTTP2, server supports multiplexing

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  h2h3 [:method: GET]

  h2h3 [:path: /pybind/pybind11/archive/v2.6.0.tar.gz]

  h2h3 [:scheme: https]

  h2h3 [:authority: github.com]

  h2h3 [user-agent: curl/7.83.1]

  h2h3 [accept: */*]

  Using Stream ID: 1 (easy handle 0x1e736f0)

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  GET /pybind/pybind11/archive/v2.6.0.tar.gz HTTP/2

  Host: github.com

  user-agent: curl/7.83.1

  accept: */*

  

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (OUT), TLS alert, decode error (562):

  [2 bytes data]

  OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while
  reading, errno 0

  Failed receiving HTTP2 data

  OpenSSL SSL_write: SSL_ERROR_SYSCALL, errno 0

  Failed sending HTTP2 data

  Connection #0 to host github.com left intact

  

          --- LOG END ---

**Comment by Li-jianqun** [comment]
another problem occurred

**Comment by csukuangfj** [comment]
```
CMake Error at pybind11-subbuild/pybind11-populate-prefix/src/pybind11-populate-stamp/download-pybind11-populate.cmake:170 (message):
Each download failed!
```

You have network connection problems with github.com. Please re-try.

**Comment by csukuangfj** [comment]
> -- No NVCC detected. Disable CUDA support

From the above logs, I suggest installing a CUDA version of PyTorch. Otherwise, it would be slow in training with CPU.

**Comment by csukuangfj** [comment]
From the output of cmake
```
-- C++ Standard version: 14
-- No NVCC detected. Disable CUDA support
```

**Comment by Li-jianqun** [comment]
cuda
tensor([[[-0.3205, -0.0260, -0.4472,  ..., -0.5320, -0.9637,  0.7955],
         [ 0.3911, -0.7258, -0.3567,  ..., -1.5768, -0.0128, -0.0643],
         [ 0.1947,  0.5352, -1.1755,  ..., -0.2569,  0.1924, -0.4802],
         ...,
         [-0.6839, -0.1884,  0.0419,  ...,  1.5066, -0.7203, -0.0287],
         [ 0.3719, -0.5363,  0.7420,  ..., -0.0720, -0.8032, -0.2815],
         [ 0.1199, -0.4554, -1.5693,  ...,  1.5446,  0.0928,  0.7194]]],
       device='cuda:0') tensor([[[-0.4588, -0.7632,  1.9258,  ..., -1.3756, -1.4427,  0.7067],
         [ 0.5199, -0.3741,  1.4006,  ..., -0.4292, -0.2924,  1.9492],
         [-0.7315, -0.4770, -0.0570,  ..., -0.2565, -0.8705, -0.0698],
         ...,
         [ 1.0323, -0.3076,  0.6142,  ..., -0.2427,  1.6642, -1.1886],
         [ 0.8142, -0.4148, -1.7596,  ..., -0.3202, -0.6493, -1.1421],
         [ 1.2979,  0.5924,  0.8514,  ...,  0.0588,  2.7043,  0.0136]]],
       device='cuda:0') tensor([[ 12, 193,  57,  28,  97,  48, 247, 134,  31,  55, 196, 252, 189,  78,
           8,  72, 243, 192]], device='cuda:0') tensor([[  0,   0,  18, 248]], device='cuda:0')
torch.Size([1, 248, 256]) torch.Size([1, 19, 256]) torch.Size([1, 18]) torch.Size([1, 4])
Traceback (most recent call last):
  File "/data5/E2E_Smnet/test_fastrnnt.py", line 30, in <module>
    simple_loss, (px_grad, py_grad) = fast_rnnt.rnnt_loss_simple(lm=lm,
  File "/data3/env/Miniconda/envs/pytorch1.10_streaming/lib/python3.9/site-packages/fast_rnnt-1.2-py3.9-linux-x86_64.egg/fast_rnnt/rnnt_loss.py", line 306, in rnnt_loss_simple
    scores_and_grads = mutual_information_recursion(
  File "/data3/env/Miniconda/envs/pytorch1.10_streaming/lib/python3.9/site-packages/fast_rnnt-1.2-py3.9-linux-x86_64.egg/fast_rnnt/mutual_information.py", line 293, in mutual_information_recursion
    scores = MutualInformationRecursionFunction.apply(px, py, pxy_grads,
  File "/data3/env/Miniconda/envs/pytorch1.10_streaming/lib/python3.9/site-packages/fast_rnnt-1.2-py3.9-linux-x86_64.egg/fast_rnnt/mutual_information.py", line 157, in forward
    ans = _fast_rnnt.mutual_information_forward(px, py, boundary, p)
RuntimeError: Failed to find native CUDA module, make sure that you compiled the code with K2_WITH_CUDA.

**Comment by Li-jianqun** [comment]
Did the compilation go wrong?

**Comment by csukuangfj** [comment]
How did you compile fast_rnnt? Do you have the compilation logs?

The error logs show that you have compiled a CPU version of fast_rnnt.
